#!/bin/bash

jupyter serverextension enable --py jupyter-server-proxy --sys-prefix
jupyter labextension install @jupyter-widgets/jupyterlab-manager \
                             @pyviz/jupyterlab_pyviz \
                             jupyter-leaflet \
                             dask-labextension
