#!/bin/bash

# enable jupyter server proxy
jupyter serverextension enable --py jupyter_server_proxy --sys-prefix

# enable ipywidgets nbextension (for qgrid)
jupyter nbextension enable --py --sys-prefix widgetsnbextension

# install desired jupyter lab extensions
jupyter labextension install @jupyter-widgets/jupyterlab-manager \
                             @pyviz/jupyterlab_pyviz \
                             jupyter-leaflet \
                             dask-labextension \
                             qgrid
