#!/bin/bash

# enable jupyter server proxy
jupyter serverextension enable --py jupyter_server_proxy --sys-prefix

# enable ipywidgets nbextension (for qgrid)
jupyter nbextension enable --py --sys-prefix widgetsnbextension

# manual git clone of qgrid fork
git clone --depth=1 https://github.com/qzchenwl/qgrid qgrid.git

# install desired jupyter lab extensions
jupyter labextension install @jupyter-widgets/jupyterlab-manager \
                             @pyviz/jupyterlab_pyviz \
                             jupyter-leaflet \
                             dask-labextension \
                             qgrid.git/js/
                             
# remove intermediary qgrid fork
rm -rf qgrid.git
